
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: source_customer_dbt_model
      description: "snowflake source"
      database: SNOWFLAKE_SAMPLE_DATA
      schema: TPCDS_SF100TCL
      tables:
          - name: CUSTOMER 
            description: "The primary key for this table"    
            
sources:
  - name: source_customer_dbt_model
    schema: TPCDS_SF100TCL
    database: SNOWFLAKE_SAMPLE_DATA

    tables:
      - name: CUSTOMER                   